version: '2.2'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'no'
    container_name: 'Avirata'
    command: sh -c "npm install && ng serve --host 0.0.0.0"
    volumes:
      - .:/app
     # - .:/app/node_modules
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true